-- Raw tables for the common Ergast/Kaggle Formula 1 dataset.
-- Column names use uppercase identifiers expected by the analytics views.
-- Required session variables:
-- SET F1_DATABASE = 'F1_ANALYTICS';
-- SET F1_RAW_SCHEMA = 'RAW';

USE DATABASE IDENTIFIER($F1_DATABASE);

CREATE TABLE IF NOT EXISTS IDENTIFIER($F1_RAW_SCHEMA || '.RAW_CIRCUITS') (
    CIRCUITID NUMBER(38, 0),
    CIRCUITREF VARCHAR,
    NAME VARCHAR,
    LOCATION VARCHAR,
    COUNTRY VARCHAR,
    LAT FLOAT,
    LNG FLOAT,
    ALT NUMBER(38, 0),
    URL VARCHAR
);

CREATE TABLE IF NOT EXISTS IDENTIFIER($F1_RAW_SCHEMA || '.RAW_CONSTRUCTORS') (
    CONSTRUCTORID NUMBER(38, 0),
    CONSTRUCTORREF VARCHAR,
    NAME VARCHAR,
    NATIONALITY VARCHAR,
    URL VARCHAR
);

CREATE TABLE IF NOT EXISTS IDENTIFIER($F1_RAW_SCHEMA || '.RAW_CONSTRUCTOR_RESULTS') (
    CONSTRUCTORRESULTSID NUMBER(38, 0),
    RACEID NUMBER(38, 0),
    CONSTRUCTORID NUMBER(38, 0),
    POINTS FLOAT,
    STATUS VARCHAR
);

CREATE TABLE IF NOT EXISTS IDENTIFIER($F1_RAW_SCHEMA || '.RAW_CONSTRUCTOR_STANDINGS') (
    CONSTRUCTORSTANDINGSID NUMBER(38, 0),
    RACEID NUMBER(38, 0),
    CONSTRUCTORID NUMBER(38, 0),
    POINTS FLOAT,
    POSITION NUMBER(38, 0),
    POSITIONTEXT VARCHAR,
    WINS NUMBER(38, 0)
);

CREATE TABLE IF NOT EXISTS IDENTIFIER($F1_RAW_SCHEMA || '.RAW_DRIVERS') (
    DRIVERID NUMBER(38, 0),
    DRIVERREF VARCHAR,
    NUMBER VARCHAR,
    CODE VARCHAR,
    FORENAME VARCHAR,
    SURNAME VARCHAR,
    DOB DATE,
    NATIONALITY VARCHAR,
    URL VARCHAR
);

CREATE TABLE IF NOT EXISTS IDENTIFIER($F1_RAW_SCHEMA || '.RAW_DRIVER_STANDINGS') (
    DRIVERSTANDINGSID NUMBER(38, 0),
    RACEID NUMBER(38, 0),
    DRIVERID NUMBER(38, 0),
    POINTS FLOAT,
    POSITION NUMBER(38, 0),
    POSITIONTEXT VARCHAR,
    WINS NUMBER(38, 0)
);

CREATE TABLE IF NOT EXISTS IDENTIFIER($F1_RAW_SCHEMA || '.RAW_LAP_TIMES') (
    RACEID NUMBER(38, 0),
    DRIVERID NUMBER(38, 0),
    LAP NUMBER(38, 0),
    POSITION NUMBER(38, 0),
    TIME VARCHAR,
    MILLISECONDS NUMBER(38, 0)
);

CREATE TABLE IF NOT EXISTS IDENTIFIER($F1_RAW_SCHEMA || '.RAW_PIT_STOPS') (
    RACEID NUMBER(38, 0),
    DRIVERID NUMBER(38, 0),
    STOP NUMBER(38, 0),
    LAP NUMBER(38, 0),
    TIME TIME,
    DURATION VARCHAR,
    MILLISECONDS NUMBER(38, 0)
);

CREATE TABLE IF NOT EXISTS IDENTIFIER($F1_RAW_SCHEMA || '.RAW_QUALIFYING') (
    QUALIFYID NUMBER(38, 0),
    RACEID NUMBER(38, 0),
    DRIVERID NUMBER(38, 0),
    CONSTRUCTORID NUMBER(38, 0),
    NUMBER NUMBER(38, 0),
    POSITION NUMBER(38, 0),
    Q1 VARCHAR,
    Q2 VARCHAR,
    Q3 VARCHAR
);

CREATE TABLE IF NOT EXISTS IDENTIFIER($F1_RAW_SCHEMA || '.RAW_RACES') (
    RACEID NUMBER(38, 0),
    YEAR NUMBER(38, 0),
    ROUND NUMBER(38, 0),
    CIRCUITID NUMBER(38, 0),
    NAME VARCHAR,
    DATE DATE,
    TIME TIME,
    URL VARCHAR,
    FP1_DATE DATE,
    FP1_TIME TIME,
    FP2_DATE DATE,
    FP2_TIME TIME,
    FP3_DATE DATE,
    FP3_TIME TIME,
    QUALI_DATE DATE,
    QUALI_TIME TIME,
    SPRINT_DATE DATE,
    SPRINT_TIME TIME
);

CREATE TABLE IF NOT EXISTS IDENTIFIER($F1_RAW_SCHEMA || '.RAW_RESULTS') (
    RESULTID NUMBER(38, 0),
    RACEID NUMBER(38, 0),
    DRIVERID NUMBER(38, 0),
    CONSTRUCTORID NUMBER(38, 0),
    NUMBER VARCHAR,
    GRID NUMBER(38, 0),
    POSITION NUMBER(38, 0),
    POSITIONTEXT VARCHAR,
    POSITIONORDER NUMBER(38, 0),
    POINTS FLOAT,
    LAPS NUMBER(38, 0),
    TIME VARCHAR,
    MILLISECONDS NUMBER(38, 0),
    FASTESTLAP NUMBER(38, 0),
    RANK NUMBER(38, 0),
    FASTESTLAPTIME VARCHAR,
    FASTESTLAPSPEED FLOAT,
    STATUSID NUMBER(38, 0)
);

CREATE TABLE IF NOT EXISTS IDENTIFIER($F1_RAW_SCHEMA || '.RAW_SEASONS') (
    YEAR NUMBER(38, 0),
    URL VARCHAR
);

CREATE TABLE IF NOT EXISTS IDENTIFIER($F1_RAW_SCHEMA || '.RAW_SPRINT_RESULTS') (
    RESULTID NUMBER(38, 0),
    RACEID NUMBER(38, 0),
    DRIVERID NUMBER(38, 0),
    CONSTRUCTORID NUMBER(38, 0),
    NUMBER VARCHAR,
    GRID NUMBER(38, 0),
    POSITION NUMBER(38, 0),
    POSITIONTEXT VARCHAR,
    POSITIONORDER NUMBER(38, 0),
    POINTS FLOAT,
    LAPS NUMBER(38, 0),
    TIME VARCHAR,
    MILLISECONDS NUMBER(38, 0),
    FASTESTLAP NUMBER(38, 0),
    FASTESTLAPTIME VARCHAR,
    STATUSID NUMBER(38, 0)
);

CREATE TABLE IF NOT EXISTS IDENTIFIER($F1_RAW_SCHEMA || '.RAW_STATUS') (
    STATUSID NUMBER(38, 0),
    STATUS VARCHAR
);
